### ISSUE TITLE
Status of this script

### ISSUE THREAD

**Issue by CorruptedzIncline** [RectangularObject/UniversalHBE#1]
Microsoft store has a very common bug for around 80% of its users where Right Control registers as Left Control
This makes it impossible to open the script, can you fix it by making the gui pop up immediately or sum?

**Comment by RectangularObject** [comment]
I'm not updating this until synapse v3 releases. If you want to use this on fluxus, [join my discord server](https://discord.gg/9zYPyFX4CJ) and use the [community patch](https://discord.com/channels/264070659036938251/878420400181219348/1124532199241297951) someone else made. I do not want to use UWP Roblox.
